[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.6.0"

[[constraint]]
  name = "github.com/donovanhide/eventsource"
  branch = "master"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  name = "github.com/lightningnetwork/lnd"
  version = "0.4.1-beta"

[[constraint]]
  name = "github.com/op/go-logging"
  version = "1.0.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[prune]
  go-tests = true
  unused-packages = true
